"""add text field to proviso

Revision ID: 0b5b8e0a3f2b
Revises: ddb20ed60266
Create Date: 2026-08-18 06:33:43.483476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b5b8e0a3f2b'
down_revision: Union[str, Sequence[str], None] = 'ddb20ed60266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
