"""добавление индексво в таблицы

Revision ID: 40b4bd1fc50c
Revises: c92024000b9d
Create Date: 2026-08-19 03:17:26.981983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b4bd1fc50c'
down_revision: Union[str, Sequence[str], None] = 'c92024000b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_buyer_id'), 'comments', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_comments_task_id'), 'comments', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_task_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_buyer_id'), table_name='comments')
    # ### end Alembic commands ###
