"""add to user_id

Revision ID: 43407791ac64
Revises: 40b4bd1fc50c
Create Date: 2026-08-19 05:36:52.626551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43407791ac64'
down_revision: Union[str, Sequence[str], None] = '40b4bd1fc50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_comments_buyer_id'), table_name='comments')
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.drop_constraint(op.f('comments_buyer_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.drop_column('comments', 'buyer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('buyer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_buyer_id_fkey'), 'comments', 'users', ['buyer_id'], ['id'])
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.create_index(op.f('ix_comments_buyer_id'), 'comments', ['buyer_id'], unique=False)
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
