"""изменены поля таск и провисо

Revision ID: 48767e28ad5a
Revises: 18cf2580075b
Create Date: 2026-08-19 19:22:02.261621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48767e28ad5a'
down_revision: Union[str, Sequence[str], None] = '18cf2580075b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE provision CASCADE")
    op.add_column('provision', sa.Column('task_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'provision', ['task_id'])
    op.create_foreign_key(None, 'provision', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_proviso_id_key'), 'tasks', type_='unique')
    op.drop_constraint(op.f('tasks_proviso_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'proviso_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('proviso_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('tasks_proviso_id_fkey'), 'tasks', 'provision', ['proviso_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('tasks_proviso_id_key'), 'tasks', ['proviso_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'provision', type_='foreignkey')
    op.drop_constraint(None, 'provision', type_='unique')
    op.drop_column('provision', 'task_id')
    # ### end Alembic commands ###
