"""move text from task to proviso

Revision ID: c92024000b9d
Revises: 0b5b8e0a3f2b
Create Date: 2026-08-18 06:46:38.537611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92024000b9d'
down_revision: Union[str, Sequence[str], None] = '0b5b8e0a3f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provision', sa.Column('text', sa.Text(), nullable=False))
    op.drop_constraint(op.f('tasks_proviso_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'provision', ['proviso_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tasks', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_proviso_id_fkey'), 'tasks', 'provision', ['proviso_id'], ['id'])
    op.drop_column('provision', 'text')
    # ### end Alembic commands ###
