"""add inn to sellers

Revision ID: ddb20ed60266
Revises: 68a90f6254a9
Create Date: 2026-08-18 05:45:13.781838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb20ed60266'
down_revision: Union[str, Sequence[str], None] = '68a90f6254a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('inn', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'inn')
    # ### end Alembic commands ###
