"""добавлениндекс в OutBoxSub

Revision ID: fb9ce9f01764
Revises: 8b162575e21e
Create Date: 2026-09-08 15:16:25.392660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9ce9f01764'
down_revision: Union[str, Sequence[str], None] = '8b162575e21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outboxsub', sa.Column('last_attempt_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_outboxsub_failed_at'), 'outboxsub', ['failed_at'], unique=False)
    op.create_index(op.f('ix_outboxsub_processed_at'), 'outboxsub', ['processed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outboxsub_processed_at'), table_name='outboxsub')
    op.drop_index(op.f('ix_outboxsub_failed_at'), table_name='outboxsub')
    op.drop_column('outboxsub', 'last_attempt_at')
    # ### end Alembic commands ###
