from app.routers.repositories.comment_rep import CommRepositories
from app.routers.repositories.submission_rep import UserSubRepositories
from app.routers.repositories.task_rep import TaskRepositories
from app.routers.repositories.category_rep import CategoryRepositories